name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'
        include-prerelease: true
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
          versionSpec: '5.x'
          
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.10
      
    - run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"
        echo "AssemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
        echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
        
    - name: Change base-tag in index.html from / to /uri-query-editor
      run: sed -i 's/<base href="\/" \/>/<base href="\/uri-query-editor\/" \/>/g' src/UriQueryEditor/wwwroot/index.html

    - name: Publish UI
      run: dotnet publish src/UriQueryEditor/UriQueryEditor.csproj -c Release -o release/ui --nologo /p:version=${{ steps.gitversion.outputs.semVer }}
    
    - name: 'Deploy UI'
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/ui/wwwroot
